pipeline {
  agent none
  stages {
    stage('Back-end') {
      agent {
        docker { image 'maven:3.8.1-adoptopenjdk-11' }
      }
      steps {
        sh 'mvn --version'
      }
    }
    stage('Front-end') {
      agent {
        docker { image 'node:16-alpine' }
      }
      steps {
        sh 'node --version'
      }
    }
  }
  post {
    // Allocate an agent specifically for this post-action
    // This runs no matter what (Success, Failure, or Aborted)
        always {
             node {
                echo 'Cleaning up test containers...'
                // The '|| true' ensures the pipeline doesn't crash if the container was never created
                sh 'docker image prune -f'
             }
        }
        success {
             node {
                  echo 'Tests passed! Cleaning up Docker images...'
                  sh 'docker image prune -f'
             }
        }
  }
}
