@Library('sharedlib') _

pipeline {
    agent any 
    environment {
        imgname = 'python-app:latest'
    }
    stages {
        stage('Build python images') {
            steps {
               dir('my-first-pipeline') {
                    sh 'docker build -t ${imgname} .' 
               }
            }
        }
        stage('Run Python App') {
            steps {
                    dir('my-first-pipeline') {
                    // Runs the container, mounts the workspace, and executes the app
                    sh 'docker run --rm -v $(pwd):/app -w /app ${imgname} python app.py'
                }
            }
        }
        stage('Build and push'){
            steps {
                dockerloginfile($imgname)
            }
        }
    }
}
