pipeline {
    agent {
        docker { 
            image 'eclipse-temurin:21-jdk'
            args '-u root'
        }
    }
    stages {
        stage('Build') {
            steps {
                checkout scm
                dir('3-java-jenkins-docker-app') {
                    sh 'apt update -y && apt install maven -y'
                    sh 'mvn clean package'
                }
            }
        }
        stage('Test') {
            steps {
                dir('3-java-jenkins-docker-app') {
                    sh 'mvn test'
                }
            }
        }        
    }
}
