pipeline {
    agent {
        docker { 
            image 'eclipse-temurin:21-jdk'
            args '-u root'
        }
    }
    stages {
        stage('Checkout Source Code') {
            steps {
                // 1. This clones your GitHub repository into the container workspace
                checkout scm 
            }
        }
        stage('Build') {
            steps {
                sh 'apt update -y && apt install maven -y'
                sh 'mvn clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
        }
        stage('Docker Build') {
            steps {
                sh 'docker build -t java-jenkins-docker:latest .'
            }
        }
        stage('Docker Run') {
            steps {
                sh 'docker run --rm java-jenkins-docker:latest'
            }
        }        
    }
}
