pipeline {
    agent {
        docker { 
            image 'eclipse-temurin:21-jdk'
            args '-u root'
        }
    }
    stages {
        stage('Debug Layout') {
            steps {
                    checkout scm
                    // Prints the current files inside the Jenkins console log
                    sh 'ls -la' 
            }
        }
        stage('Build') {
            steps {
                checkout scm
                sh 'apt update -y && apt install maven -y'
                sh 'mvn clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
        }
        stage('Docker Build') {
            steps {
                sh 'docker build -t java-jenkins-docker:latest .'
            }
        }
        stage('Docker Run') {
            steps {
                sh 'docker run --rm java-jenkins-docker:latest'
            }
        }        
    }
}
